version: '3.1'
services: 
  mongo:
    image: 'mongo'

  redis-server:
    image: 'redis'

  web:
    build:
      context: .
      dockerfile: .docker/app.development.dockerfile 
    volumes:
      - /usr/app/node_modules 
      - .:/usr/app
    ports: 
      - '8000:5000'

  tests:
    build:
      context: .
      dockerfile: .docker/app.development.dockerfile 
    volumes:
      - /usr/app/node_modules 
      - .:/usr/app
    command: ["yarn", "run", "test:watch"]
